apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $k, $v := .Values.backend.labels }}
    {{ $k }}: {{ $v }}
    {{- end }}
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    {{- range $k, $v := .Values.backend.labels }}
    {{ $k }}: {{ $v }}
    {{- end }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port | default 8000 }}
      targetPort: {{ .Values.backend.containerPort }}
