gateway:
  name: eg
  namespace: gateway

hostName: "grafana.example.com"
namespace: monitoring

grafana:
  HTTPRoute:
    name: grafana-route
    syncWaves: "1"
    path: /
    serviceName: prometheus-crd-grafana
    port: 80
