namespace: dev
frontend:
  image:
    tag: v0.1.35
backend:
  image:
    tag: v0.1.24
config:
  host: dev-db.c0nu6occexai.us-east-1.rds.amazonaws.com
app:
  HTTPRoute:
    name: dev-app-route
    hostName: "dev.example.com"
externalSecret:
  remoteRef:
    key: arn:aws:secretsmanager:us-east-1:466872246229:secret:rds!db-01cbfbc8-9e69-4556-8968-5684a2ffb86e-8jD5rK
