namespace: stage

app:
  HTTPRoute:
    name: app-stage-route
    hostName: "app.stage.com"
  

frontend:
  image:
    tag: v0.1.30
backend:
  image:
    tag: v0.1.16


irsaArn: blank
secretsmanagerArn: blank