namespace: dev
app:
  HTTPRoute:
    name: app-dev-route
    hostName: "app.dev.com"
frontend:
  image:
    tag: v0.1.30
backend:
  image:
    tag: v0.1.19
config:
  host: dev-db.c0nu6occexai.us-east-1.rds.amazonaws.com
