namespace: dev
frontend:
  image:
    tag: v0.1.35
backend:
  image:
    tag: v0.1.24
config:
  host: dev-db.c0nu6occexai.us-east-1.rds.amazonaws.com
app:
  HTTPRoute:
    name: dev-app-route
    hostName: "dev.example.com"
