namespace: prod

app:
  HTTPRoute:
    name: app-prod-route
    hostName: "app.prod.com"
  

frontend:
  image:
    tag: v0.1.30
backend:
  image:
    tag: v0.1.16


irsaArn: blank
secretsmanagerArn: blank