namespace: dev
frontend:
  image:
    tag: v0.1.32
backend:
  image:
    tag: v0.1.21
config:
  host: dev-db.c0nu6occexai.us-east-1.rds.amazonaws.com


gateway:
  name: eg
  namespace: gateway

dev:
  namespace: dev
  HTTPRoute:
    name: dev-app-route
    syncWaves: "1"
    hostName: "dev.example.com" 
    path: /
    serviceName: frontend
    port: 80