gateway:
  name: eg
  namespace: gateway

namespace: argocd

argocd:
  HTTPRoute:
    name: argocd-route
    syncWaves: "1"
    hostName: "argocd.example.com"
    path: /
    serviceName: argocd-server
    port: 80


dbConfig:
  name: db-credentials
  dbname: posgressdb
  host: "dev-db.c0nu6occexai.us-east-1.rds.amazonaws.com"
  port: 5432