
#secrete store
secretStore:
  name: cluster-secret-store
  provider:
    service: SecretsManager
    region: us-east-1
  serviceAccount:
    name: external-secrets-sa
    namespace: external-secrets
#service account
serviceAccount:
  name: external-secrets-sa
  namespace: external-secrets
  roleArn: arn:aws:iam::466872246229:role/external-secrets-2026010410405734200000000d
