namespace: dev
serviceAccount:
  name: dev-sa
  roleArn: arn:aws:iam::466872246229:role/external-secrets-2026010116275415680000000f
secretStore:
  name: ClusterSecretStore
  provider:
    service: SecretsManager
    region: us-east-1
  serviceAccount:
    name: external-secrets-sa
    namespace: external-secrets
externalSecret:
  name: db-credentials
  target: db-credentials
  remoteRef:
    key: db
