namespace: dev
serviceAccount:
  roleArn: arn:aws:iam::466872246229:role/external-secrets-2026010221270320570000000f
externalSecret:
  remoteRef:
    key: arn:aws:secretsmanager:us-east-1:466872246229:secret:rds!db-9ff44757-580b-4b28-80eb-599f8a708d56-wrTv8s
