namespace: dev

secretStore:
  name: dev-secret-store
  provider:
    service: SecretsManager
    region: us-east-1
  serviceAccount:
    name: external-secrets-sa
    namespace: external-secrets
externalSecret:
  name: db-credentials
  target: db-credentials
  remoteRef:
    key: db
