namespace: dev
serviceAccount:
  name: secret-manager-sa
  annotations: blank #irsaArn
secretStore:
  name: secretstore
  provider:
    service: SecretsManager
    region: us-east-1
externalSecret:
  name: db-credentials
  target: db-credentials #must match with the backebd secret ref
  remoteRef:
    key: blank #secret manager arn
