namespace: dev
secretStore:
  name: cluster-secret-store
  provider:
    service: SecretsManager
    region: us-east-1
  serviceAccount:
    name: external-secrets-sa
    namespace: external-secrets
externalSecret:
  name: db-credentials
  target: db-credentials
  remoteRef:
    key: arn:aws:secretsmanager:us-east-1:466872246229:secret:rds!db-9ff44757-580b-4b28-80eb-599f8a708d56-wrTv8s
serviceAccount:
  name: external-secrets-sa
