namespace: dev
serviceAccount:
  roleArn: arn:aws:iam::466872246229:role/external-secrets-2025123011365546590000000f
externalSecret:
  remoteRef:
    key: arn:aws:secretsmanager:us-east-1:466872246229:secret:rds!db-3f88a512-c730-434a-9c78-d2a23a9af1b8-kYiDqj
