namespace: dev
serviceAccount:
  roleArn: arn:aws:iam::466872246229:role/external-secrets-2026010116275415680000000f
externalSecret:
  remoteRef:
    key: arn:aws:secretsmanager:us-east-1:466872246229:secret:rds!db-b97e0365-952a-45bb-9bb0-b39d229c5511-1xxjjk
