apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  POSTGRES_DB: {{ .Values.config.dbname }}
  POSTGRES_HOST: {{ .Values.config.host }}
  POSTGRES_PORT: {{ .Values.config.port }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  POSTGRES_DB: backenddb
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"